openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  /users/save:
    post:
      tags:
      - user-service
      operationId: add
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Users'
  /jobcontacts/save:
    post:
      tags:
      - job-contact-service
      operationId: add_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobContact'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JobContact'
  /users/get/{id}:
    get:
      tags:
      - user-service
      operationId: get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Users'
  /users/all:
    get:
      tags:
      - user-service
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
  /jobcontacts/{user}:
    get:
      tags:
      - job-contact-service
      operationId: getUserContacts
      parameters:
      - name: user
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobContact'
  /jobcontacts/get/{id}:
    get:
      tags:
      - job-contact-service
      operationId: get_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JobContact'
  /jobcontacts/all:
    get:
      tags:
      - job-contact-service
      operationId: getAll_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobContact'
  /users/delete/{id}:
    delete:
      tags:
      - user-service
      operationId: remove
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /jobcontacts/delete/{id}:
    delete:
      tags:
      - job-contact-service
      operationId: remove_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    Users:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
        enabled:
          type: string
    JobContact:
      type: object
      properties:
        id:
          type: integer
          format: int64
        candidate:
          type: string
        type:
          type: string
        description:
          type: string
        positionId:
          type: integer
          format: int64
        date:
          type: string
          format: date
